on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: kapasrijkubacr.azurecr.io
        username: ${{ secrets.acr_kapasrijkubacr_username }}
        password: ${{ secrets.acr_kapasrijkubacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/go/plain/container/Application" -f  "go/plain/container/Application/Dockerfile" -t kapasrijkubacr.azurecr.io/democluster:${{ github.sha }}
        docker push kapasrijkubacr.azurecr.io/democluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_democluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep demo-clusterbcc0 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace demo-clusterbcc0`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: demo-clusterbcc0
        container-registry-url: kapasrijkubacr.azurecr.io
        container-registry-username: ${{ secrets.acr_kapasrijkubacr_username }}
        container-registry-password: ${{ secrets.acr_kapasrijkubacr_password }}
        secret-name: democlusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: demo-clusterbcc0
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          kapasrijkubacr.azurecr.io/democluster:${{ github.sha }}
        imagepullsecrets: |
          democlusterdockerauth