on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aaaatiwarishubregistry.azurecr.io
        username: ${{ secrets.acr_aaaatiwarishubregistry_username }}
        password: ${{ secrets.acr_aaaatiwarishubregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/go/plain/container/Application" -f  "go/plain/container/Application/Dockerfile" -t aaaatiwarishubregistry.azurecr.io/kptestcluster:${{ github.sha }}
        docker push aaaatiwarishubregistry.azurecr.io/kptestcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kptestcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kptestclusterb042 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kptestclusterb042`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kptestclusterb042
        container-registry-url: aaaatiwarishubregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_aaaatiwarishubregistry_username }}
        container-registry-password: ${{ secrets.acr_aaaatiwarishubregistry_password }}
        secret-name: kptestclustedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kptestclusterb042
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          aaaatiwarishubregistry.azurecr.io/kptestcluster:${{ github.sha }}
        imagepullsecrets: |
          kptestclustedockerauth